new remote list system using mapped variables

diff --git a/autossh/autossh b/autossh/autossh
--- a/autossh/autossh
+++ b/autossh/autossh
@@ -1,15 +1,10 @@
-# Declares remote info maps
-declare -A availableSystems
-declare -A availableSystemHosts
 
-# Loads remote hosts to maps if file exists
+# Loads lits of remote keys
 remoteHostsListFile=${AUTOSSH_REMOTE_HOSTS:-~/ssh_hosts_list}
-if [ -f $remoteHostsListFile ]; then
-	source $remoteHostsListFile
-fi
+remoteHosts=($(grep -E "^remoteHost" "$remoteHostsListFile" | awk '{print $2}'))
 
 # Stores number of available remotes
-remoteCount=${#availableSystems[@]}
+remoteCount=${#remoteHosts}
 
 # Loads params
 while getopts :hexc:r:d:u: opt; do
@@ -45,7 +40,7 @@ if ! [ "$showHelp" = "on" ] && ! [ "$editMode" = "on" ]; then
 	declare -a fileNames
 	if [ $# -ge $OPTIND ]; then
 		args=( $@ )
-		for i in `seq $((OPTIND-1)) $((${#args[@]}-1))`; do
+		for i in $(seq $((OPTIND-1)) $((${#args[@]}-1))); do
 			fileNames=(${fileNames[@]} ${args[$i]})
 		done
 		unset args
@@ -56,25 +51,27 @@ fi
 alignCols=${cols:-30}
 
 # Sorts remotes alphabetically by name
-sortKeys() {
-	for id in "${!availableSystems[@]}"; do
+sortHosts() {
+	for id in "${remoteHosts[@]}"; do
 		echo $id;
 	done | sort -r > ~/.keys.tmp
-	entry=`tail -n -1 ~/.keys.tmp`
+	entry=$(tail -n -1 ~/.keys.tmp)
 	i=1
-	while [ ! "$entry" = "" ]; do
-		printf -v entry "%-"$alignCols"s (%s)" $entry ${availableSystemHosts[$entry]}
+	while [ ! "$entry" == "" ]; do
+		loadRemoteParams $entry
+		printf -v entryInfo "%-"$alignCols"s (%s)" "$hostName" "$systemHost"
+		sortedHosts[$i]="$entryInfo"
 		sortedKeys[$i]="$entry"
 		i=$((i + 1))
 		sed -ie '$d' ~/.keys.tmp
-		entry=`tail -n -1 ~/.keys.tmp`
+		entry=$(tail -n -1 ~/.keys.tmp)
 	done
 	rm ~/.keys.tmp
 }
 
 # Shows usage / help text
 showUsage() {
-	scriptName=`basename "$0"`
+	scriptName=$(basename "$0")
 	echo "Usage:"
 	echo "  $scriptName [opt] [opt arg] [files]"
 	echo
@@ -83,7 +80,7 @@ showUsage() {
 	echo "           Prompts to connect to remote hosts list. Sets remote name to use 10 characters, trimming if longer and completing with whitespaces if shorter."
 	echo
 	echo "  $scriptName -xr 2"
-	echo "           Connects you to the #2 remote if available, else prompts with the remote hosts list. Prints the command used to connect."
+	echo "           Connects you to the #2 remote (alphabetic order by key) if available, else prompts with the remote hosts list. Prints the command used to connect."
 	echo
 	echo "Options:"
 	echo "  -h       Shows this help text and exits."
@@ -105,22 +102,26 @@ showUsage() {
 	if [ $remoteCount -eq 0 ]; then
 		echo
 		echo "You have no remotes registered. To register a remote, create a AUTOSSH_REMOTE_HOSTS file, export its path to the AUTOSSH_REMOTE_HOSTS variable and follow the pattern, one for each entry:"
-		echo "  name=\"Remote-name-no-spaces-or-special-characters\""
-		echo "  availableSystems[\$name]=/path/to/your/private/key"
-		echo "  availableSystemHosts[\$name]=user@host.address"
+		echo "  remoteHost remote-key-no-spaces-or-special-characters && {"
+		echo "    hostName=\"Your host name written however you want it to\""
+		echo "    sshKey=/path/to/your/private/key (or only key file if in ~/.ssh)"
+		echo "    userName=remote host user"
+		echo "    address=remote host address"
+		echo "  }"
 	fi
 }
 
 # Selects a remote to connect to
 selectRemote() {
-	select selectedRemote in "${sortedKeys[@]}" Exit
+	select selectedRemote in "${sortedHosts[@]}" "Exit (0)"
 	do
-		case $selectedRemote in
-			Exit)
+		case $REPLY in
+			0|$((remoteCount + 1)))
 			  echo 0;
 				break;;
 			*)
-				if [ $REPLY -gt ${#sortedKeys[@]} ] || [ $REPLY -lt 1 ]; then
+				if [ $REPLY -gt ${remoteCount} ] || [ $REPLY -lt 1 ]; then
+					echo >&2 "You picked an invalid remote. Try again or Exit"
 					shift;
 				else
 					echo $REPLY;
@@ -131,25 +132,28 @@ selectRemote() {
 }
 
 # Loads remote params
-getRemoteParams() {
-	for i in "${!sortedKeys[@]}"; do
-		if [ $i -eq $1 ]; then
-			system=`echo ${sortedKeys[$i]} | cut -d" " -f1`
-			systemKey=${availableSystems[$system]}
-			systemHost=${availableSystemHosts[$system]}
-			break
-		fi
-	done
+loadRemoteParams() {
+	localRemote="$1"
+	function remoteHost { test $1 = $localRemote; }
+	source $remoteHostsListFile
+	if [ ! -f $sshKey ]; then
+		sshKey=~/.ssh/$sshKey
+	fi
+	if [ ! -f $sshKey ]; then
+		echo "Host key for '$localRemote' not found. Check your '$AUTOSSH_REMOTE_HOSTS' file."
+		exit 1
+	fi
+	systemHost="$userName@$address"
 }
 
 # Connects to remote using SSH
 connectToRemote() {
 	if [ "$explainMode" = "on" ]; then
 		echo "The following command will be executed:"
-		echo "ssh -i $systemKey $systemHost"
+		echo "ssh -i $sshKey $systemHost"
 	fi
-	echo "Connecting to $system.."
-	ssh -i $systemKey $systemHost
+	echo "Connecting to $hostName.."
+	ssh -i $sshKey $systemHost
 }
 
 # Downloads files from remote using SCP
@@ -157,14 +161,14 @@ downloadFromRemote() {
 	if [ ${#fileNames[@]} -eq 0 ]; then
 		echo "You need to specify a folder or file to download."
 	else
-		fileNames=`echo "\"${fileNames[@]}\""`
+		fileNames=$(echo "\"${fileNames[@]}\"")
 		if [ "$explainMode" = "on" ]; then
 			echo "The following command will be executed:"
-			echo "scp -i $systemKey $systemHost:${fileNames} \"$downloadPath\""
+			echo "scp -i $sshKey $systemHost:${fileNames} \"$downloadPath\""
 		fi
-		echo "Downloading files from $system.."
+		echo "Downloading files from $hostName.."
 		# Workaround because the fuckin bash is surrounding my string with single-quotes
-		eval `echo "scp -i $systemKey $systemHost:${fileNames} \"$downloadPath\""`
+		eval $(echo "scp -i $sshKey $systemHost:${fileNames} \"$downloadPath\"")
 	fi
 }
 
@@ -175,26 +179,25 @@ uploadToRemote() {
 	else
 		if [ "$explainMode" = "on" ]; then
 			echo "The following command will be executed:"
-			echo "scp -i $systemKey \"${fileNames[@]}\" $systemHost:\"$uploadPath\""
+			echo "scp -i $sshKey \"${fileNames[@]}\" $systemHost:\"$uploadPath\""
 		fi
-		echo "Uploading files to $system.."
-		scp -i $systemKey "${fileNames[@]}" $systemHost:"$uploadPath"
+		echo "Uploading files to $hostName.."
+		scp -i $sshKey "${fileNames[@]}" $systemHost:"$uploadPath"
 	fi
 }
 
 # Creates a sample hosts file
 createSampleHost() {
 	if ! [ -f $remoteHostsListFile ]; then
-		echo "#!/bin/bash" >> $remoteHostsListFile
-		echo >> $remoteHostsListFile
 		echo "# REMOTES LIST" >> $remoteHostsListFile
 		echo >> $remoteHostsListFile
-		echo "name=\"Remote-name-no-spaces-or-special-characters\"" >> $remoteHostsListFile
-		echo "availableSystems[\$name]=/path/to/your/private/key" >> $remoteHostsListFile
-		echo "availableSystemHosts[\$name]=user@host.address" >> $remoteHostsListFile
+		echo "remoteHost remote-key-no-spaces-or-special-characters && {" >> $remoteHostsListFile
+		echo "  hostName=\"Your host name written however you want it to\"" >> $remoteHostsListFile
+		echo "  sshKey=/path/to/your/private/key (or only key file if in ~/.ssh)" >> $remoteHostsListFile
+		echo "  userName=remote host user" >> $remoteHostsListFile
+		echo "  address=remote host address" >> $remoteHostsListFile
+		echo "}" >> $remoteHostsListFile
 		echo >> $remoteHostsListFile
-		echo "unset name" >> $remoteHostsListFile
-		echo "# END REMOTES LIST" >> $remoteHostsListFile
 	fi
 }
 
@@ -211,14 +214,12 @@ start() {
 		exit 0
 	fi
 
-	declare -a sortedKeys; sortKeys
+	declare -a sortedHosts; declare -a sortedKeys; sortHosts
 
 	if [ -z ${remote+x} ]; then
 		remote=$(selectRemote)
-	fi
-
-	if [ $remote -lt 0 ] || [ $remote -gt $remoteCount ]; then
-		echo "You picked an invalid remote."
+	elif [ $remote -lt 0 ] || [ $remote -gt $remoteCount ]; then
+		echo "You picked an invalid remote. Try again or Exit"
 		remote=$(selectRemote)
 	fi
 
@@ -226,7 +227,7 @@ start() {
 		exit 1
 	fi
 
-	getRemoteParams $remote
+	loadRemoteParams ${sortedKeys[$remote]}
 
 	if ! [ -z "${downloadPath+x}" ]; then
 		downloadFromRemote
